## ansible-playbook -i hosts -u vagrant -k initial_server_setup.yaml
---
- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
  gather_facts: false
  vars:
    create_user: vagrant
    copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    sys_packages: [ 'curl', 'git', 'ufw','ca-certificates','software-properties-common' ]

  tasks:
    - name: Make sure we have a 'vagrant' group
      group:
        name: vagrant
        state: present

    - name: Allow 'vagrant' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%vagrant'
        line: '%vagrant ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Create a new regular user with sudo privileges
      user:
        name: "{{ create_user }}"
        state: present
        groups: vagrant
        append: true
        createhome: true
        shell: /bin/bash

    - name: Set authorized key for remote user
      authorized_key:
        user: "{{ create_user }}"
        state: present
        key: "{{ copy_local_key }}"

    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'

    - name: Disable password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'

    - name: Set hostname
      hostname:
        name: '{{ inventory_hostname }}'

    - name: Replace a localhost entry with our own
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: 127.0.1.1 {{ inventory_hostname }}

    - name: Add hosts mappings to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '{{ hostvars[item].ansible_host }}.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }}  {{item}}"
        state: present
      become: yes
      with_items: "{{ groups.all }}"

    - name: Insert ENV in .bashrc for calicoctl
      blockinfile:
        path: /home/{{ create_user }}/.bashrc
        block: |
          export DATASTORE_TYPE=kubernetes
          export KUBECONFIG=~/.kube/config

    - name: Update apt
      apt: update_cache=yes

    - name: Install required system packages
      apt: name={{ sys_packages }} state=latest

    - name: UFW - Allow SSH connections
      ufw:
        rule: allow
        name: OpenSSH

    - name: Allow all access to tcp port 6443 for connecting to k8s api-server
      ufw:
        rule: allow
        port: '6443'
        proto: tcp

    - name: Allow all access to tcp port 179 for BGP
      ufw:
        rule: allow
        port: '179'
        proto: tcp

    - name: UFW - Deny all other incoming traffic by default
      ufw:
        state: enabled
        policy: deny
        direction: incoming

    - name: Copy calicoctl
      copy:
        src: /Users/mpeng/Downloads/calicoctl
        dest: /usr/local/bin/calicoctl
        mode: '0555'
