## ansible-playbook -i hosts -u vagrant k8s-dependencies.yaml
---
- hosts: all
  become: yes
  tasks:
   - name: disable swap, if any
     become: true
     shell: swapoff -a

   - name: Disable swap in /etc/fstab
     lineinfile:
       path: /etc/fstab
       state: absent
       regexp: '^/swap.img'

   - name: install APT Transport HTTPS
     apt:
       name: apt-transport-https
       state: present

   - name: add Docker apt-key
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

   - name: Get the Ubuntu release
     command: lsb_release -cs
     register: lsb_release

   - name: add Docker' APT repository
     apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable
      state: present
      filename: 'docker'

   - name: install Docker
     apt:
       name: docker-ce
       state: present
       update_cache: true

   - name: Create /etc/docker/daemon.json file
     file:
       path: "/etc/docker/daemon.json"
       state: touch

   - name: Change the cgroupdriver to systemd
     blockinfile:
      path: "/etc/docker/daemon.json"
      block: |
        {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
             "max-size": "100m"
          },
          "storage-driver": "overlay2"
        }
      marker: ""

   - name: Create /etc/systemd/system/docker.service.d directory
     file:
      path: "/etc/systemd/system/docker.service.d"
      state: directory

   - name: Force systemd to reload
     systemd:
        daemon_reload: yes

   - name: Restart service docker, and not touch the state
     systemd:
       name: docker
       state: restarted

   - name: Enable service docker, and not touch the state
     service:
       name: docker
       enabled: yes

   - name: Change file ownership, group and permissions
     file:
       path: /var/run/docker.sock
       mode: '666'

   - name: add Kubernetes apt-key
     apt_key:
#       url: https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   - name: add Kubernetes' APT repository
     apt_repository:
#      repo: deb https://mirrors.aliyun.com/kubernetes/apt kubernetes-xenial main
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

   - name: install kubelet
     apt:
       name: kubelet=1.16.3-00
       state: present
       update_cache: true

   - name: install kubeadm
     apt:
       name: kubeadm=1.16.3-00
       state: present

   - name: install kubectl
     apt:
       name: kubectl=1.16.3-00
       state: present
       force: yes
