## ansible-playbook -u vagrant -k -s -i hosts k8s-nodes.yaml

---
- hosts: master
  become: yes
  gather_facts: true
  tasks:
    - name: Get Join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set Join Command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: worker
  become: yes
  tasks:
    - name: Join Cluster
      shell: "{{ hostvars['k8s-master'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
